### ISSUE TITLE
bug with pagination

### ISSUE THREAD

**Issue by wekerle** [ashl1/datatables-rowsgroup#2]
hello Alexey Shildyakov. I recently used your  Datatables feature plugin that groups rows (merge cells vertically) according to specified columns. It is very nice and useful and I really like it.... However, I found a bug. When I use a dataTable witch has pagenumbers (paging: true), it doesn't work completely. The problem is, it only works for the first page, but when i go to second page, it doesn't work. I created an example and I attached it to this message. You will need to unzip it and open it with any browser.
[rowgroup2.zip](https://github.com/ashl1/datatables-rowsgroup/files/167059/rowgroup2.zip)

**Comment by wekerle** [comment]
hello Alexey Shildyakov. I fork your code, i fixed this bug, it was easy to fix. Also i create an another example with your rowGroup plugin. I create a pull request, if you want you can accept it

**Comment by ashl1** [comment]
Thank you. I'll verify it soon.
Could you please tell me your full name to add to license file?

**Comment by ashl1** [comment]
Extract your name from commit

**Comment by wck821829906** [comment]
@wekerle @ashl1  It is very strange that it doesn't work for me when go to second page, my datatables-rowsgroup.js version is 2.0.0

**Comment by ashl1** [comment]
@wck821829906 Could you provide live example of not working behavior? You can use http://live.datatables.net/ for example or any service you want.

**Comment by ayenzJ** [comment]
@wck821829906 it was the same for me, it only works on the first pagination. I'm also using version 2.0. please help

**Comment by jrsaavedra1022** [comment]
@ashl1  Hola, me gusto mucho el plugin, sin embargo tuve un pequeño inconveniente al momento de hacer destroy en las tablas y seguir gratificando sin recargar la página, la única solución que me dio resultado fue agregar está linea de código, por si le interesa a alguien o a ti.

$(document).on( 'destroy.dt', function ( e, settings ) {
	var api = new $.fn.dataTable.Api( settings );
	api.off('order.dt');
	api.off('preDraw.dt');
	api.off('column-visibility.dt');
	api.off('search.dt');
	api.off('page.dt');
	api.off('length.dt');
	api.off('xhr.dt');
});

**Comment by caodinhhuy** [comment]
I use this plugin for my project and I get same error, always go to first page when reload.
this is my Included libraries: JSZip 2.5.0, DataTables 1.10.18, Buttons 1.5.4, Column visibility 1.5.4, Flash export 1.5.4, HTML5 export 1.5.4
I fixed this error, in _updateOrderAndDraw function, I change row 235
before: this.table.draw()
after:    this.table.draw('page')
about 'page' parameter: ordering and search will not be updated and the paging position held where is was ([https://datatables.net/reference/api/draw()](https://datatables.net/reference/api/draw()))
now it working fine
